# joint_limits.yaml overrides URDF limits, keeps everything organized

#downscaled velocity and accel scaling factor for safety
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  q1:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  q2:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  q3:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
  q4:
    has_velocity_limits: true
    max_velocity: 2.00
    has_acceleration_limits: false
    max_acceleration: 0
