# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    uorover_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

uorover_arm_controller:
  ros__parameters:
    joints:
      - q1
      - q2
      - q3
      - q4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity